#!/usr/bin/env python3
"""Publish the receipt-backed V3.1 terminal navigation projection."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

from chaoyang.governance.common import (
    AUTHORITY_PATH,
    RECEIPT_PATH,
    REPO_ROOT,
    TASK_STATE_PATH,
    artifact_ref,
    atomic_json,
    load_json,
    now_iso,
    publish_bundle,
    validate_artifact_ref,
)


CURRENT_INDEX = REPO_ROOT / "tasks/current/INDEX.json"
STATUS_PATH = REPO_ROOT / "docs/current/STATUS.json"
OUTPUT_BASE = REPO_ROOT / "_run/current/three_stream_v31_terminal_status"
LIVE = {"PENDING", "READY", "CLAIMED", "RUNNING", "WAIT_GPU_RESOURCE"}


def _write_once(path: Path, value: dict[str, object]) -> None:
    encoded = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True).encode() + b"\n"
    if path.exists() or path.is_symlink():
        if path.is_file() and path.read_bytes() == encoded:
            return
        raise RuntimeError(f"immutable artifact conflict: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_json(path, value)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--expected-revision", required=True, type=int)
    parser.add_argument("--publication-id", default="publication_0001")
    args = parser.parse_args()
    if re.fullmatch(r"publication_[0-9]{4}", args.publication_id) is None:
        raise RuntimeError("publication-id must match publication_NNNN")
    output_root = OUTPUT_BASE / args.publication_id
    if output_root.exists() or output_root.is_symlink():
        raise RuntimeError(f"fresh terminal-status publication required: {output_root}")

    receipt = load_json(RECEIPT_PATH)
    if int(receipt.get("governance_revision", -1)) != args.expected_revision:
        raise RuntimeError("CAS revision mismatch before terminal-status publication")
    for reference in receipt.get("files", {}).values():
        errors = validate_artifact_ref(reference)
        if errors:
            raise RuntimeError("current receipt conflict: " + "; ".join(errors))

    state = load_json(TASK_STATE_PATH)
    if state.get("next_task") is not None or any(
        row.get("status") in LIVE for row in state.get("tasks", [])
    ):
        raise RuntimeError("terminal-status publication requires no live task")
    index = load_json(CURRENT_INDEX)
    if index.get("status") != "PASS_NO_ACTIVE_TASKS" or index.get("task_packets") != []:
        raise RuntimeError("terminal-status publication requires an empty current index")

    status = load_json(STATUS_PATH)
    if status.get("schema_version") != "chaoyang-three-stream-shallow-status-v2":
        raise RuntimeError("terminal STATUS.json must be generated by the V3.1 terminal builder")
    if status.get("final_claims", {}).get("PIPELINE_COMPLETE") is not False:
        raise RuntimeError("blocked V3.1 terminal status cannot claim pipeline completion")
    if status.get("resource_use", {}).get("gpu_used") is not False:
        raise RuntimeError("V3.1 terminal status conflicts with recorded CPU-only execution")

    created = now_iso()
    output_root.mkdir(parents=True)
    published = publish_bundle(
        load_json(AUTHORITY_PATH),
        state,
        event_type="THREE_STREAM_V31_TERMINAL_STATUS_PUBLISHED",
        expected_revision=args.expected_revision,
        generator_path=Path(__file__),
        task_packet_index_path=CURRENT_INDEX,
        task_packet_index_value=index,
    )
    result = {
        "schema_version": "chaoyang-three-stream-v31-terminal-status-publication-v1",
        "status": "PASSED",
        "published_at": created,
        "governance_revision": published["governance_revision"],
        "generation_id": published["generation_id"],
        "status_projection": artifact_ref(STATUS_PATH),
        "execution_registered": False,
        "claim_limit": (
            "Navigation/status publication only. Blocked evidence remains blocked; no model, "
            "training, metric, control, or deployment authority is granted."
        ),
    }
    result_path = output_root / "RESULT.json"
    _write_once(result_path, result)
    print(json.dumps({**result, "result": artifact_ref(result_path)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
